version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWEORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumnes:
      - postgres_data:/var/lib/postgresql/data

volumnes:
  postgres_data:
